"""add lend fields

Revision ID: 036656c7da82
Revises: 
Create Date: 2025-07-25 08:22:48.631922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel                

# revision identifiers, used by Alembic.
revision: str = '036656c7da82'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('borrower_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('claim', sa.Column('lent_at', sa.DateTime(), nullable=True))
    op.add_column('claim', sa.Column('returned_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_claim_borrower_email'), 'claim', ['borrower_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_borrower_email'), table_name='claim')
    op.drop_column('claim', 'returned_at')
    op.drop_column('claim', 'lent_at')
    op.drop_column('claim', 'borrower_email')
    # ### end Alembic commands ###
