"""add status field to Claim

Revision ID: 0c30e293e8aa
Revises: c0d23fdb0a5e
Create Date: 2025-07-28 09:56:23.756510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c30e293e8aa'
down_revision: Union[str, Sequence[str], None] = 'c0d23fdb0a5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('status', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_claim_borrower_email'), table_name='claim')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_claim_borrower_email'), 'claim', ['borrower_email'], unique=False)
    op.drop_column('claim', 'status')
    # ### end Alembic commands ###
