"""play session table

Revision ID: 28b7e5f12075
Revises: 036656c7da82
Create Date: 2025-07-25 16:41:27.329402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '28b7e5f12075'
down_revision: Union[str, Sequence[str], None] = '036656c7da82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playsession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playsession_qr'), 'playsession', ['qr'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playsession_qr'), table_name='playsession')
    op.drop_table('playsession')
    # ### end Alembic commands ###
