"""play session table

Revision ID: b0aa0b8f02e1
Revises: 28b7e5f12075
Create Date: 2025-07-26 14:45:39.851442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel                


# revision identifiers, used by Alembic.
revision: str = 'b0aa0b8f02e1'
down_revision: Union[str, Sequence[str], None] = '28b7e5f12075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
