"""add user table

Revision ID: c0d23fdb0a5e
Revises: b0aa0b8f02e1
Create Date: 2025-07-27 15:54:40.897683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel                


# revision identifiers, used by Alembic.
revision: str = 'c0d23fdb0a5e'
down_revision: Union[str, Sequence[str], None] = 'b0aa0b8f02e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
